[package]
name = "broadcast_gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
crossbeam = "0.8.4"
dotenvy = "0.15.7"
rdkafka = "0.36.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
socket2 = "0.5.7"
